server:
  port: 8081

spring:
  application:
    name: game
  jpa:
    show-sql: true
    properties.hibernate.format_sql: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
